[modelpriors]
# layers: min/max no of layers (half space is not counted)
# z: min/max layer depth [km]
# vs: min/max shear speed [km/s]
# vpvs: min/max vp/vs ratio
# mohoest: estimate of mohodepth with standard deviation [km, km] (optional)
# rfnoise_corr: correlation of receiver function noise
# rfnoise_sigma: min/max value of receiver function noise parameter
# swdnoise_corr: correlation of dispersion curves noise (set to 0)
# swdnoise_sigma: min/max value of dispersion curve noise parameter [km/s]
layers = 1, 20
z = 0, 20
vs = 0.5, 7.0
vpvs = 1.73
mohoest = None

rfnoise_corr = 1.
rfnoise_sigma = 1e-5, 0.2

swdnoise_corr = 0.
swdnoise_sigma = 1e-5, 0.2

[initparams]
# propdist: standard deviation of proposal distribution of different parameters
# 	vs [km/s], z_move [km], cell birth/deah, noise parameter [km/s], vpvs
# acceptance: min/max acceptance rate [%]
# rcond: cutoff value for receiver functions noise-correlation parameter
nchains = 100
iter_burnin = 2000000
iter_main = 1000000

propdist =  0.05, 0.05, 0.05, 0.01, 0.0
acceptance = 40, 45

thickmin = 0.1
lvz = None
hvz = None

rcond= 1e-5

station = 'obs'
savepath = 'results'
maxmodels = 500000
